// <auto-generated />
using HNTitles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HNTitles.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20210605072729_RemoveItemEntryClass")]
    partial class RemoveItemEntryClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("HNTitles.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HnItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("PreviousItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HNTitles.Item", b =>
                {
                    b.HasOne("HNTitles.Item", "PreviousItem")
                        .WithMany()
                        .HasForeignKey("PreviousItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreviousItem");
                });
#pragma warning restore 612, 618
        }
    }
}
